/*
 * TIMER0_Config.h
 *
 *  Created on: ٣٠‏/٠٩‏/٢٠٢١
 *      Author: Ahmed Gaber
 */

#ifndef MTIMER0_MTIMER0_CONFIG_H_
#define MTIMER0_MTIMER0_CONFIG_H_


/*
 * 1- NO_PRESCALER
 * 2- PRESCALER_8
 * 3- PRESCALER_64
 * 4- PRESCALER_256
 * 5- PRESCALLER_1024
 * 6- EXTERNAL_EVENT_FALLING_EDGE
 * 7- EXTERNAL_EVENT_RISING_EDGE
 */
#define TIMER_PRESCALER PRESCALLER_1024
 /*
  * 1- TIMER0_OVF_MODE
  * 2- TIMER0_CTC_MODE
  */
#define TIMER0_MODE TIMER0_FAST_PWM
#define TIMER0_PWM_MODE  FAST_PWM_NON_INVERTING

#define TIMER0_CTC_VALUE 10

#define TIMER_PRELOAD_VALUE 0


#endif /* MTIMER0_MTIMER0_CONFIG_H_ */
